### ISSUE TITLE
useEffect implementation

### ISSUE THREAD

**Issue by rudixops** [VolkenoMakers/react-native-quiz-multiple-choice#1]
I am trying to fetch the data from API/AsyncStorage with following code

  useEffect(() => {
    const getQuiz = async () => {
      const quiz = await AsyncStorage.getItem('onboarding');
      setQuiz(JSON.parse(quiz));
    };
    getQuiz();
  }, []);

but it doesn't work , the error says "at least 2 elements must be added"

Thank you for creating this package

**Comment by babacarMbengue12** [comment]
fixed on version 1.0.3
